# ╔════════════════════════════════════════════════╗
# ║ SECTION: Imports                               ║
# ╚════════════════════════════════════════════════╝
from tools.smart_marker_injector import auto_function
from tools.obvious_router import auto_function
# @auto_function
"""Debug: test

Revision ID: 8e028c7f96cb
Revises: ccd6d2de1a2d
Create Date: 2025-07-08 02:37:46.650035

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e028c7f96cb'
down_revision = 'ccd6d2de1a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
