# ╔════════════════════════════════════════════════╗
# ║ SECTION: Imports                               ║
# ╚════════════════════════════════════════════════╝
from tools.smart_marker_injector import auto_function
from tools.obvious_router import auto_function
# @auto_function
"""base schema

Revision ID: b396f1972d4d
Revises: ef9aeb6adb02
Create Date: 2025-07-08 17:41:33.971398

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b396f1972d4d'
down_revision = 'ef9aeb6adb02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.String(length=100), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_reports_id'), 'scan_reports', ['id'], unique=False)
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_scan_reports_id'), table_name='scan_reports')
    op.drop_table('scan_reports')
    # ### end Alembic commands ###
