"""Auto: add missing columns

Revision ID: ccd6d2de1a2d
Revises: fe92549eee91
Create Date: 2025-07-07 19:42:58.147202

"""

# ╔════════════════════════════════════════════════╗
# ║ SECTION: Imports                               ║
# ╚════════════════════════════════════════════════╝
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccd6d2de1a2d'
down_revision = 'fe92549eee91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_reports_id', table_name='scan_reports')
    op.drop_table('scan_reports')
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('scan_reports',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scan_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('report_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='scan_reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scan_reports_pkey')
    )
    op.create_index('ix_scan_reports_id', 'scan_reports', ['id'], unique=False)
    # ### end Alembic commands ###
