"""Auto: add missing columns

Revision ID: ef9aeb6adb02
Revises: 8e028c7f96cb
Create Date: 2025-07-08 02:43:01.860031

"""

# ╔════════════════════════════════════════════════╗
# ║ SECTION: Imports                               ║
# ╚════════════════════════════════════════════════╝
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9aeb6adb02'
down_revision = '8e028c7f96cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'accuracy',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
